#!/usr/bin/env Rscript
# 
#################################################################
# bamtofastq_from_manifest.R
# This script takes an iRODs manifest and generates an sh file with a series of command job submission to import, sort and transform to fastq, CRAMs from iRODs
# 
#  The Project folder should have the following  structure before running this program:
#  /My_project_folder/
#     metadata/manifests/My_cram_manifest_INFO_from_iRODS.txt
# 
# The program will create the  following directories:
# /My_project_folder/
#     /fastqs
#     /logs
#       /cramtofastqs
#  
# 
#Author: Martin Del Castillo Velasco-Herrera - mdc1@sanger.ac.uk
###################################################################
progname<-"bamtofastq_from_manifest.R.R"
#Loading Libraries
suppressMessages(library(optparse))
suppressMessages(library(ggplot2))
suppressMessages(library(RColorBrewer))

#Get the options for the script
####### Set the options list of the program
option_list<- list(
  make_option(c("--manifest"), action="store_true", default=NA, type="character", help="This is the project iRODs manifest file name generated by sequencescape project ID number using Build_manifest_from_irods_cram_information.R
                IT should be locatet in the folder /projectdir/metadata/ for this command to work"), 
  make_option(c("--projectdir"), action="store_true", type="character", default=NA, help="This is the location where the main project folder is (if provided, else it will assume the current directory)"),
  make_option(c("--studyID"), action="store_true", type="character", default=NA, help="This is the sequencescape study_ID"),
  make_option(c("--ref"), action="store_true", type="character", default=NA, help="Path to the reference genome FASTA otherwise present in BAM will be used (OPTIONAL)"),
  make_option(c("--mem"), action="store_true", type="character", default="6000", help="This is the RAM memory amount (in Mb) set for the conversion jobs")
)
#### Indicate that the file follows to the options used
parser<- OptionParser(usage = paste(progname, " [options] --manifest My_cram_manifest_INFO_from_iRODS.txt, --studyID 6510 --projectdir  /My_project_folder/ --pdxID CDS2_Tumour --ref /My/Path/Genomes/genome.fa ",sep=""), option_list=option_list)
arguments<- parse_args(parser, positional_arguments = 0) # no files after the options shoudl be provided
opt<-arguments$options

#FOR testing purposes


#Verify that the outidr was set
if(is.na(opt$projectdir)){
  projectdir<-paste(getwd(),"/",sep="")
} else {
  projectdir<-opt$projectdir
}
#Verify there is a study ID provided
if(is.na(opt$studyID)){
  stop(paste0("NO STUDY ID provides, Check file or see the help for requirements"))
}
studyid<-opt$studyID
#Verify there reference provided - if provided
if(!is.na(opt$ref)){
  if(!file.exists(opt$ref)){
    stop(paste0("The reference genome provided doesn't exist:", opt$ref))
  } 
}

#Verify that the input manifest exitst was set 
manifdir<-file.path(projectdir, "metadata", "manifests")
manif_name<-file.path(manifdir, opt$manifest)
if(!file.exists(manif_name)){
  stop(paste("The manifest file:", manif_name, "doesn't exits. Check file or see the help for requirements", sep=""))
}

if(!file.exists(manif_name)){
  stop(paste("The manifest file:", manif_name, "doesn't exits. Check file or see the help for requirements", sep=""))
}

#Write some output starting message
write(paste("#########################################\n", progname, date(),"The study ID found from manifest name is: ",studyid, "\nThe Manifest provided:", manif_name,"\n",
            "The projectdir provided is:", projectdir, "\n", 
            "The study is:", opt$studyID, "\n", 
            "The project manifest found is: ",manif_name, "\n",sep=" "), stdout())

#######################################################################
#Defining the directories for the analyses and GENERAL VARIABLES
#Set of folders for the outputs
fqfolder<-file.path(projectdir, "fastqs/finalfastqs")
logfolder<-paste(projectdir, "/logs", sep="")
fqlogfolder<-paste(projectdir, "/logs/finalfqs",sep="")

#Make the folders
dir.create(fqfolder)
dir.create(fqlogfolder, recursive = TRUE)

#PAHTS to the programs required
#Checking if samtools is visible
if (length(system("which samtools &> /dev/null", intern=T))==0 ) {
  warning("samtools is not available.")
} else { # Print samtools version
  write(paste( "Found samtools version:"), stdout())
  write(paste( system("samtools --version | head -n 2", intern=T), sep=" "), stdout())
}
samtools<-"samtools"

######################
#EXMAPLEs of job to transform cram from iRODs to fastq
# bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o 6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e 6352_project_tests/logs/cramtofastqs/cramtofq_21.e 'iget /seq/illumina/runs/38/38900/lane1/plex21/38900_1#21.cram - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools collate -u --threads 4 -O - |/software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 6352_project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 6352_project_tests/fastqs/6352STDY10233950_R2.fastq.gz -n '

#############################################################################################
# 1. Read the file  manifest file  ------------------
manif<-read.csv(manif_name, header=TRUE, stringsAsFactors=FALSE, sep="\t")
#To take as a test I will generate things first for the biggest sample
#test_sampl<-manif[manif$total_reads==228701454,]

#############################################################################################
# 2. Create the sh file that will submit  the jobs for the iRODS cram to fastq transformation  ------------------
i<-0
fq1<-NULL
fq2<-NULL
smp_runid<-NULL
cmds<-NULL
for (i in 1:dim(manif)[1]){
  fastq1<-NULL
  fastq2<-NULL
  sdoutf<-NULL
  serrf<-NULL
  tsrunid<-NULL
  temp<-manif[i,]
  tsrunid<- paste0(temp$sample_supplier_name,"_",temp$id_run,"_",temp$lane,"#",temp$tag_index)
  cmd<-NULL
  # give name to errorfiles
  sdoutf<-file.path(fqlogfolder, paste("bammtofq_",i,".o", sep = ""))
  serrf<-file.path(fqlogfolder, paste("bamtofq_",i,".e", sep = ""))
  #For the fastqs
  fastq1<-file.path(fqfolder, paste(tsrunid, "_R1.fastq.gz", sep=""))
  fastq2<-file.path(fqfolder, paste(tsrunid, "_R2.fastq.gz", sep=""))
  #Section that creates the farm command to submit the job the job submission 
  # should look like this
  #bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o 6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e 6352_project_tests/logs/cramtofastqs/cramtofq_21.e ' samtools collate -u --threads 4 -O - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 6352_project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 6352_project_tests/fastqs/6352STDY10233950_R2.fastq.gz '
  if(is.na(opt$ref)){
    cmd<-as.character(paste("bsub -q normal -M ", opt$mem, " -R",shQuote(paste0("select[mem>",opt$mem,"] rusage[mem=", opt$mem,"] span[hosts=1]")) , " -n 6 -o ", sdoutf," -e ",serrf, 
             " ' ", samtools, " collate -u --threads 6 -O ", temp$Final_BAM[1], " | ",
             samtools, " fastq --threads 6 -N -1 ",fastq1, " -2 ", fastq2, "'",
             sep=""))  
  } else{
    ref<-paste0("--reference ", opt$ref )
    cmd<-as.character(paste("bsub -q normal -M ", opt$mem, " -R",shQuote(paste0("select[mem>",opt$mem,"] rusage[mem=", opt$mem,"] span[hosts=1]")) , " -n 6 -o ", sdoutf," -e ",serrf, 
             " ' ", samtools, " collate ", ref, " -u --threads 6 -O ", temp$Final_BAM[1], " | ",
             samtools, " fastq ", ref, " --threads 6 -N -1 ",fastq1, " -2 ", fastq2, "'",
             sep=""))
  }
  #ADD the jobs
  cmds<-c(cmds,cmd)
  fq1<-c(fq1,fastq1)
  fq2<-c(fq2,fastq2)
  smp_runid<-c(smp_runid, tsrunid)
}

if(!is.na(opt$ref)){
  manif$reference<-opt$ref
}
#add the fastq info to the manifest
manif$final_fastq1<-fq1
manif$final_fastq2<-fq2
manif$sample_fqrunid<-smp_runid
#Create the sh file 
write.table(c("#!/bin/sh", cmds), file=file.path(projectdir,"scripts", paste0(studyid,"_bamtofastq_final_jobs.sh")), quote = F, col.names = F, row.names = F, sep = "\n")

#############################################################################################
# 5. Save new full manifest   ------------------
#Create new manifest name
tnw_manif<-basename(manif_name)
tnw_manif<-gsub(".txt", "_fqs.txt", tnw_manif[length(tnw_manif)])
write.table(manif,file=file.path(manifdir, tnw_manif), quote = F, col.names = T, row.names = F, sep = "\t") 
