#!/usr/bin/env Rscript
# 
#################################################################
# make_kallisto_jobs_from_manifest.R
# This script takes an iRODs manifest and generates an sh file with a series of command job submission to import, sort and transform to fastq, CRAMs from iRODs
# 
#  The Project folder should have the following  structure before running this program:
#  /My_project_folder/
#     metadata/manifests/My_cram_manifest_INFO_from_iRODS.txt
# 
# The program will create the  following directories:
# /My_project_folder/
#     /fastqs
#     /logs
#       /cramtofastqs
#  
# 
#Author: Martin Del Castillo Velasco-Herrera - mdc1@sanger.ac.uk
###################################################################
progname<-"make_kallisto_jobs_from_manifest.R"
#Loading Libraries
suppressMessages(library(optparse))
suppressMessages(library(ggplot2))
suppressMessages(library(RColorBrewer))

#Get the options for the script
####### Set the options list of the program
option_list<- list(
  make_option(c("--manifest"), action="store_true", default=NA, type="character", help="This is the project iRODs manifest file name generated by sequencescape project ID number using Build_manifest_from_irods_cram_information.R
                IT should be locatet in the folder /projectdir/metadata/ for this command to work"), 
  make_option(c("--projectdir"), action="store_true", type="character", default=NA, help="This is the location where the main project folder is (if provided, else it will assume the current directory)"),
  make_option(c("--studyID"), action="store_true", type="character", default=NA, help="This is the sequencescape study_ID"),
  make_option(c("--index"), action="store_true", type="character", default=NA, help="This is kallisto index"),
  make_option(c("--kallisto"), action="store_true", type="character", default=NA, help="This is kallisto singularity image"),
  make_option(c("--mem"), action="store_true", type="character", default="6000", help="This is the RAM memory amount (in Mb) set for the conversion jobs")
)
#### Indicate that the file follows to the options used
parser<- OptionParser(usage = paste(progname, " [options] --manifest My_cram_manifest_INFO_from_iRODS.txt, --studyID 6510 --projectdir  /My_project_folder/ --pdxID CDS2_Tumour --ref /My/Path/Genomes/genome.fa ",sep=""), option_list=option_list)
arguments<- parse_args(parser, positional_arguments = 0) # no files after the options shoudl be provided
opt<-arguments$options

#FOR testing purposes

#Verify that the outidr was set
if(is.na(opt$projectdir)){
  projectdir<-paste(getwd(),"/",sep="")
} else {
  projectdir<-opt$projectdir
}
#Verify there is a study ID provided
if(is.na(opt$studyID)){
  stop(paste0("NO STUDY ID provides, Check file or see the help for requirements"))
}
studyid<-opt$studyID

#Verify that the input manifest exitst was set 
manif_name<-file.path(opt$manifest)
if(!file.exists(manif_name)){
  stop(paste("The manifest file:", manif_name, "doesn't exits. Check file or see the help for requirements", sep=""))
}

#Verify the index exist
kindex<-opt$index
if(!file.exists(kindex)){
  stop(paste("The kallisto index file:", kindex, "doesn't exits. Check file or see the help for requirements", sep=""))
}

#Verify the singularity image
kallisto_sif<-opt$kallisto
if(!file.exists(kallisto_sif)){
  stop(paste("The kallisto singularity file:", kallisto_sif, "doesn't exits. Check file or see the help for requirements", sep=""))
}

#Set of folders for the outputs
kallisto_folder<-file.path(projectdir,"analysis", "kallisto")
logfolder<-paste(projectdir, "/logs", sep="")
kallsito_logfolder<-paste(projectdir, "/logs/kallisto",sep="")

#Write some output starting message
write(paste("#########################################\n", progname, 
            date(),"The study ID found from manifest name is: ",studyid, "\nThe Manifest provided:", manif_name,"\n",
            "The projectdir provided is:", projectdir, "\n", 
            "The study is:", studyid, "\n", 
            "The index from kallisto is:", kindex, "\n", 
            "The kallisto sif:", kallisto_sif, "\n", 
            "The outdir", kallisto_folder , "\n", 
            "The project manifest found is: ",manif_name, "\n",sep=" "), stdout())

#######################################################################
#Defining the directories for the analyses and GENERAL VARIABLES

#Make the folders
dir.create(kallisto_folder, recursive=TRUE)
dir.create(kallsito_logfolder, recursive = TRUE)

#PAHTS to the programs required
######################
#EXMAPLEs of job to transform cram from iRODs to fastq
# bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o 6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e 6352_project_tests/logs/cramtofastqs/cramtofq_21.e 'iget /seq/illumina/runs/38/38900/lane1/plex21/38900_1#21.cram - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools collate -u --threads 4 -O - |/software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 6352_project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 6352_project_tests/fastqs/6352STDY10233950_R2.fastq.gz -n '

#############################################################################################
# 1. Read the file  manifest file  ------------------
manif<-read.csv(manif_name, header=TRUE, stringsAsFactors=FALSE, sep="\t")
#To take as a test I will generate things first for the biggest sample
#test_sampl<-manif[manif$total_reads==228701454,]

#############################################################################################
# 2. Create the sh file that will submit  the jobs for the iRODS cram to fastq transformation  ------------------
i<-0
fq1<-NULL
fq2<-NULL
cmds<-NULL
for (i in 1:dim(manif)[1]){
  fastq1<-NULL
  fastq2<-NULL
  sdoutf<-NULL
  serrf<-NULL
  tsrunid<-NULL
  tmpoutdir<-NULL
  temp<-manif[i,]
  tsrunid<- paste0(temp$sample_supplier_name,"_kallisto")
  cmd<-NULL
  # give name to errorfiles
  sdoutf<-file.path(kallsito_logfolder, paste("kallisto_",i,".o", sep = ""))
  serrf<-file.path(kallsito_logfolder, paste("kallisto_",i,".e", sep = ""))
  #Set the fast
  fastq1<-temp$final_fastq1[1]
  fastq2<-temp$final_fastq2[1]
  #Set the kallisto output dir
  tmpoutdir<- file.path(kallisto_folder, temp$sample)
  #Section that creates the farm command to submit the job the job submission 
  # should look like this
  #bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o 6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e 6352_project_tests/logs/cramtofastqs/cramtofq_21.e ' samtools collate -u --threads 4 -O - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 6352_project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 6352_project_tests/fastqs/6352STDY10233950_R2.fastq.gz '
  cmd<-as.character(paste("bsub -q normal -M ", opt$mem, " -R",shQuote(paste0("select[mem>",opt$mem,"] rusage[mem=", opt$mem,"] span[hosts=1]")) , 
  " -n 8 -o ", sdoutf," -e ",serrf, 
            " 'singularity exec -e -B `pwd` -B /lustre -B ", projectdir,
            " ", kallisto_sif, " kallisto quant --rf-stranded -i ", kindex,
            " -b 100 ",
            "-t 8", 
            " -o ",  tmpoutdir, " ", fastq1, " ", fastq2, "'",
            sep=""))  
  #ADD the jobs
  cmds<-c(cmds,cmd)
}

#Create the sh file 
write.table(c("#!/bin/bash", cmds), file=file.path(projectdir,"scripts", paste0(studyid,"_kallisto_final_jobs.sh")), quote = F, col.names = F, row.names = F, sep = "\n")

