#!/usr/bin/env Rscript
#################################################################
# PDX_STAR_mapping_jobs_from_master_manif.R
# This script takes an MAster manifest generated from <STUDY>_master_manifest_creation_RNAseq.R to create series of files with a series of command job submission to import, sort, transform to fastq, map with STAR
# and generate counts with htseqcount plus some quality controls for the read nucleotide composition and TIN (currently not working)
#
#  The Project folder should have the following  structure before running this program:
#  /My_project_folder/
#   ├── manifests/My_cram_manifest_INFO_from_iRODS.txt
#   ├── bams
#   │   └── RNASEQ_UNFILT
#   ├── fastqs
#Author: Martin Del Castillo Velasco-Herrera - mdc1@sanger.ac.uk
###################################################################
progname<-"PDX_STAR_mapping_jobs_from_master_manif.R"
#Loading Libraries
suppressMessages(library(optparse))
suppressMessages(library(ggplot2))
suppressMessages(library(RColorBrewer))

#Get the options for tthe script
####### Set the options list of the program
option_list<- list(
  make_option(c("--manifest"), action="store_true", default=NA, type="character", help="This is the project iRODs manifest file name generated by sequencescape project ID number using Build_manifest_from_irods_cram_information.R
                IT should be locatet in the folder /projectdir/manifests/ for this command to work"), 
  make_option(c("--projectdir" ), action="store_true",type="character", default=NA, help="This is the location where the main project folder is (if provided, else it will assume the current directory)"),
  make_option(c("--referencedir" ), action="store_true",type="character", default=NA, help="This is the location where the mouse reference is located alongside GTF for the annotation")
)
#### Indicate that the file follows to the options used
parser<- OptionParser(usage = paste(progname, " [options] --manifest SeqscapeID_canappsID_master_manifest_wmetadata_for_proj.txt --projectdir  /My_project_folder/ --referencedir /PATH/To/my/reference ",sep=""), option_list=option_list)
arguments<- parse_args(parser, positional_arguments = 0) # no files after the options shoudl be provided
#FOR testing purposes
 # arguments<- parse_args(parser,
 #                         args=c("--manifest","6591_2775_master_manifest_wmetadata_for_proj.txt","--projectdir","/lustre/scratch124/casm/team113/projects/6591_PDX_models_Latin_America_RNAseq"), #For tests
 #                        # args=c("--manifest","6591_2775_master_manifest_wmetadata_for_proj.txt","--projectdir","/Users/mdc1/Desktop/team113sc124/projects/6591_PDX_models_Latin_America_RNAseq"), #For tests from PC
 #                         positional_arguments = 0) # no files after the options should be provided
 # 
# get command line options, if help option encountered print help and exit,
# otherwise if options not found on command line then set defaults,
opt<-arguments$options


#Verify that the projectdir was set
if(is.na(opt$projectdir)){
  projectdir<-paste(getwd(),"/",sep="")
} else {
  projectdir<-opt$projectdir
}

#Verify that the referencedir was set
if(is.na(opt$referencedir)){
  stop("No reference directory was provided !")
} else {
  refdir<- opt$referencedir
  if(!dir.exists(refdir) ){
    stop(paste0("The reference directory provided doesn't exist ! : ", refdir ))
  }

}

#Verify that the input manifest exitst was set 
manifdir<-file.path(projectdir, "metadata", "manifests")
scriptsdir<-file.path(projectdir, "scripts", "pdx_processing" )
manif_name<-file.path(manifdir,opt$manifest)
if(!file.exists(manif_name)){
  stop(paste("The manifest file:", manif_name, "doesn't exits. Check file or see the help for requirements", sep=""))
}
#Getting the study id
studyid<-unlist(strsplit(opt$manifest, split = "_",fixed = T) )[1]

#Checking if samtools is visible
if (length(system("which samtools &> /dev/null", intern=T))==0 ) {
  warning("samtools is not available.")
} else { # Print samtools version
  write(paste( "Found samtools version:"), stdout())
  write(paste( system("samtools --version | head -n 2", intern=T), sep=" "), stdout())
}
#Checking if STAR is visible
if (length(system("which STAR &> /dev/null", intern=T))==0 ) {
  warning("STAR is not available.")
} else { # Print STAR version
  write(paste( "Found STAR version:"), stdout())
  write(paste( system("STAR --version | head -n 2", intern=T), sep=" "), stdout())
}


#Write some output starting message
write(paste("#########################################\n", progname, date(),"The study ID found from manifest name is: ",studyid, "\nThe Manifest provided:", opt$manifest,"\n",
            "The projectdir provided is:", projectdir, "\n", "The project manifest found is: ",manif_name, "\n",sep=" "), stdout())

#######################################################################
#Defining the directories for the analyses and GENERAL VARIABLES

#Set of folders for the outputs
fqfolder<-file.path(projectdir, "fastqs")
logfolder<-paste(projectdir, "/logs", sep="")
fqlogfolder<-file.path(logfolder, "cramtofastqs")

#create the folder for the mapping results 
bamdir<-file.path(projectdir,"bams", "RNASEQ_UNFILT")
star_maplogdir<-file.path(logfolder, "STAR_logs")
qcpltdir<-file.path(projectdir, "qc_plots")


#Make the folders
dir.create(fqlogfolder, recursive = TRUE)
dir.create(bamdir, recursive = TRUE)
dir.create(star_maplogdir, recursive = TRUE)
dir.create(qcpltdir, recursive = TRUE)

#PAHTS to the programs required
samtools<-"samtools"
#STAR module for the latest version of STAR
#star<-"module load star/2.7.10a ; STAR"
star<-"STAR"
#STAR reference index directory and GTF for -NOD/ShiLtJ_V1 reference for PDX filtering 
#refdir - Should be equual to something like /lustre/scratch124/casm/team113/ref/NOD_ShiLtJ_V1_PDX_ref
star_nodv1_ref<-file.path(refdir, "star/ensv107_gtf_2.7.10a")
star_nodv1_ref_fasta<-file.path(refdir, "genome.fa")
star_nodv1_gtf<-file.path(refdir, "NOD_ShiLtJ_V1_PDX.ENSv107.gtf")
#Check if the files exist
if(!file.exists(star_nodv1_ref_fasta)){
  stop(psate0("Couldn't find the the reference genome fasta file: ", star_nodv1_ref_fasta ))
}
if(!file.exists(star_nodv1_gtf)){
  stop(psate0("Couldn't find the the reference genome GTF file: ", star_nodv1_gtf ))
}
if(!dir.exists(star_nodv1_ref)){
  stop(psate0("Couldn't find the the reference genome directory: ", star_nodv1_ref ))
}

######################
#EXMAPLEs of job to transform cram from iRODs to fastq
# bsub -q normal -M 8000 -R'select[mem>8000] rusage[mem=8000] span[hosts=1]' -n 4 -o /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.o -e /lustre/scratch119/casm/team113da/users/mdc1/6352_project_tests/logs/cramtofastqs/cramtofq_21.e 'iget /seq/illumina/runs/38/38900/lane1/plex21/38900_1#21.cram - | /software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools collate -u --threads 4 -O - |/software/CASM/modules/installs/samtools/samtools-1.13/bin/samtools fastq --threads 4 -1 /project_tests/fastqs/6352STDY10233950_R1.fastq.gz -2 /project_tests/fastqs/6352STDY10233950_R2.fastq.gz -n '

#############################################################################################
# 1. Read the file  manifest file  ------------------
manif<-read.csv(manif_name, header=TRUE, stringsAsFactors=FALSE, sep="\t")
manif$sample <- manif$sample_supplier_name
#Add the fastq names
#manif$fastq1 <- file.path(fqfolder, manif$sample, paste(manif$sample, gsub(".cram","", manif$cram, fixed = T), "R1.fastq.gz", sep="_")) 
#manif$fastq2 <- file.path(fqfolder, manif$sample, paste(manif$sample, gsub(".cram","", manif$cram, fixed = T), "R2.fastq.gz", sep="_")) 

#To take as a test I will generate things first for the biggest sample
#test_sampl<-manif[manif$total_reads==228701454,]

#############################################################################################
# 2. Create the sh file that will submit  the jobs for mouse mapping from FASTA transformation  ------------------

#############################################################################################
# 3. Create the per sample manifest   ------------------
#In this case since the samples were sequenced into a single lane  there is no need get a manifest with all the information per unique sample

#############################################################################################
# 4. Create the sh file that will submit the mapping with STAR agains NOD/ShiLtJ_V1 ------------------
#bsub -q long -J "4624STDY6739364_STAR" -M 90000 -R"select[mem>90000] rusage[mem=90000] span[ptile=12]" -n 12  
#-o /lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/STAR2_5_bams/logs/4624STDY6739364STAR_run.o 
#-e /lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/STAR2_5_bams/logs/4624STDY6739364STAR_run.e 
#'/software/team113/algorithms/STAR2.5/STAR-STAR_2.5.0a/bin/Linux_x86_64//STAR 
#--genomeDir /lustre/scratch119/casm/team113da/references/rat/Rnor6/STAR_2.7.9a_indexes/STAR_2.7.9a_ERCC92_rlen100_ENSv104
#--limitBAMsortRAM 153267238979 
#--runThreadN 12 
#--outFilterType BySJout 
#--outFileNamePrefix /lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/STAR2_5_bams/4624STDY6739364/4624STDY6739364_ 
#--readFilesIn /lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_1_1_1.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_2_1_1.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_3_1_1.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_4_1_1.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_5_1_1.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_6_1_1.fastq /lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_1_1_2.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_2_1_2.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_3_1_2.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_4_1_2.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_5_1_2.fastq,/lustre/scratch116/casm/team113/projects/4624_TSG_knockout_in_hiPSCs_Jyoti_Clara/fastqs/4624STDY6739364/22107_6_1_2.fastq 
#--alignSJoverhangMin 8 
#--alignSJDBoverhangMin 1 
#--outFilterMismatchNoverLmax 0.3 
#--alignIntronMin 20 
#--outFilterMismatchNmax 999 
#--alignIntronMax 1000000 
#--alignMatesGapMax 1000000 
#--outFilterMultimapNmax 1 
#--outSAMattrIHstart 0 
#--outSAMmultNmax 1 
#--outSAMstrandField intronMotif 
#--outSAMtype BAM SortedByCoordinate 
#--quantMode GeneCounts 
#--readFilesCommand zcat
#--sjdbGTFfile /lustre/scratch116/casm/team113/ref/ENSEMBL_genome_annotation_files/Human/Homo_sapiens.GRCh38.v84_ERCC92.gtf  '

#Create the two directories that will be created to store the mouse mapped files. 
refnam<-"NOD_PDXV1"
nodv1_bamfile_dir<- file.path(projectdir,"bams", "NOD_mapping", refnam)
dir.create(nodv1_bamfile_dir, recursive = T)

#Generate the set of mapping commands - NODv1
i<-1
bamfile<-NULL
cmds<-NULL
bam_path<-NULL
tmanif<-manif
for (i in 1:dim(tmanif)[1]){
  sdoutf<-NULL
  serrf<-NULL
  temp<-tmanif[i,]
  cmd<-NULL
  bam_prefix<-NULL
  bam_sampdir<-NULL
  tbamp<-NULL
  # give name to errorfiles
  sdoutf<-file.path(star_maplogdir, paste("STAR_mapping_log_",refnam,"_", i,".o", sep = ""))
  serrf<-file.path(star_maplogdir, paste("STAR_mapping_log_",refnam,"_", i,".e", sep = ""))
  bam_sampdir<-file.path(nodv1_bamfile_dir, temp$sample)
  print(paste("Creating the output directory for mapping of sample", temp$sample))
  dir.create(bam_sampdir)
  bam_prefix<-file.path(bam_sampdir, paste(temp$sample, "_", refnam, ".", sep=""))
  tbamp<-paste(bam_prefix, "Aligned.sortedByCoord.out.bam", sep="")
  #Section that creates the farm command to submit the job the job submission 
  # should look like this
  #
  cmd<-as.character(paste("bsub -q long -M 36000 -R",shQuote("select[mem>36000] rusage[mem=36000] span[hosts=1]") , " -n 12 -o ", sdoutf," -e ",serrf,
                          " '", star, " --genomeDir ", star_nodv1_ref,
                          " --outFileNamePrefix ", bam_prefix,
                          " --runThreadN 12 ",
                          " --readFilesIn ",  paste( temp$fastq1,collapse = ","), " ", paste( temp$fastq2,collapse = ","),
                          " --sjdbGTFfile ", star_nodv1_gtf,
                          " --readFilesCommand zcat",
                          " --outSAMtype BAM SortedByCoordinate",
                          #To ouput correct RG information,
                          " --outSAMattrRGline ", 
                          #
                          paste(paste(paste("ID:",temp$id_run,"_",temp$lane, "#",temp$tag_index,sep=""),paste("LB:",temp$library_id,sep=""), paste("SM:",temp$sample_supplier_name,sep=""), "CN:SC", "PL:ILLUMINA", sep=" "), collapse=" , "),
                          #ALL parameters form here are based on ENCODE's parameters for long RNAseq
                          " --outFilterType BySJout",
                          #This is important for reporting unique mappings per reads.
                          " --outFilterMultimapNmax 1", 
                          " --alignSJoverhangMin 5",
                          " --alignSJDBoverhangMin 1",
                          " --outFilterMismatchNmax 10",
                          " --outFilterMismatchNoverReadLmax 1",
                          " --alignIntronMin 20",
                          " --alignIntronMax 1000000",
                          " --alignMatesGapMax 1000000",
                          #For cufflinks compatibility
                          " --outSAMattrIHstart 0",
                          " --outSAMattributes NH   HI   NM   MD   AS   XS",
                          " --outSAMmultNmax 1", 
                          " --outSAMstrandField intronMotif",
                          "'",
                          sep=""))  
  #ADD the jobs
  cmds<-c(cmds,cmd)
  #add to the list of bampaths
  bam_path<-c(bam_path, tbamp)
}

#Add the bampaths to the manifes
manif$bam_path_nodv1<-bam_path
manif$bam_path_nodv1[!grepl("Y", manif$Proc_as_PDX, fixed=TRUE)]<-NA

#Create the sh file 
write.table(c("#!/bin/sh", cmds[grepl("Y", manif$Proc_as_PDX, fixed=TRUE)]),
 file=file.path(projectdir,"scripts","pdx_processing", paste("STAR_mapping_to_",refnam, "_jobs.sh", sep="")), quote = F, col.names = F, row.names = F, sep = "\n")



#############################################################################################
# 10. Plot the number of reads sequence d   ------------------
cols<-colorRampPalette(rev(brewer.pal(n=12,name = "Paired" )))(length(unique(manif$donor_id)))
nreads<-ggplot(data = manif, aes(x=sample_supplier_name, y=total_reads))+
  geom_bar(aes(fill=donor_id), stat = "identity")+
  scale_fill_manual(values = cols)+
  theme(legend.title = element_text(colour = "black"),
        axis.text.x = element_text(angle = 45, hjust = 1))+
  ggtitle("Number of reads sequenced by sample")+
  xlab("Supplier Sample Name")+
  ylab("Total num. of reads sequenced")

pdf(file = file.path( qcpltdir, "UNFILTER_QC_plot_totNumReads_seq_per_sample_byDonorID.pdf"), width = 20, height = 9 )
nreads
dev.off()

#############################################################################################
# 11. Save new full manifest   ------------------
#Create new manifest name
tnw_manif<-basename(manif_name)
tnw_manif<-gsub(".txt", "_wNOD_bams.txt", tnw_manif)
#Update the reference used for the files
write.table(manif,file=file.path(manifdir, tnw_manif), quote = F, col.names = T, row.names = F, sep = "\t") 
